# Generated by Django 3.0.4 on 2020-03-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouruser', '0003_auto_20200318_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(max_length=5000, verbose_name='내용'),
        ),
    ]
